<?php

namespace BlogBundle\Repository;

/**
 * testRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class testRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTrierDQL()
    {
        $query=$this->getEntityManager()->createQuery("SELECT m FROM AppBundle:Article m ORDER BY m.vue DESC ");
        return $query->getResult();
    }

}
