<?php

namespace ProduitBundle\Repository;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorisRepository extends \Doctrine\ORM\EntityRepository
{

    public function getnbrfavoris(){
        $query = $this->getEntityManager()
            ->createQuery("SELECT IDENTITY(e.produit) ,COUNT(e) FROM ProduitBundle:Favoris e GROUP BY e.produit");
        return $query->getResult();

    }
}
