blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
afficherblog:
    path:     /afficherb
    defaults: { _controller: BlogBundle:blog:afficherb }

afficherblogarticle:
    path:     /afficherarticle/{id}/
    defaults: { _controller: BlogBundle:blog:afficherarticle }
afficherblogtrier:
    path:     /afficherblogtrier
    defaults: { _controller: BlogBundle:blog:afficherblogtrier }
affichergarderie:
    path:     /affichergarderie
    defaults: { _controller: BlogBundle:blog:affichergarderie }
ajouterarticle:
    path:     /ajouterarticle
    defaults: { _controller: BlogBundle:backblog:ajouterarticle }
afficherarticle:
    path:     /afficherarticle
    defaults: { _controller: BlogBundle:backblog:afficherarticle }
supprimerarticle:
    path:     /supprimerarticle/{id}/
    defaults: { _controller: BlogBundle:backblog:supprimerarticle }
modifierarticle:
    path:     /modifierarticle/{id}/
    defaults: { _controller: BlogBundle:backblog:modifierarticle }
affichergarderieback:
    path:     /affichergarderieback
    defaults: { _controller: BlogBundle:backblog:affichergarderie }
ajoutergarderie:
    path:     /ajoutergarderie
    defaults: { _controller: BlogBundle:backblog:ajoutergarderie }
supprimergarderie:
    path:     /supprimergarderie/{id}/
    defaults: { _controller: BlogBundle:backblog:supprimergarderie }
modifiergarderie:
    path:     /modifiergarderie/{id}/
    defaults: { _controller: BlogBundle:backblog:modifiergarderie }
CalculMontant:
    path:     /CalculMontant/{id}/
    defaults: { _controller: BlogBundle:blog:CalculMontant }
affichergarderie1:
    path:     /affichergarderie1/{id}/
    defaults: { _controller: BlogBundle:blog:affichergarderie1 }
ajoutercour:
    path:     /ajoutercour
    defaults: { _controller: BlogBundle:backblog:ajoutercour }
affichercour:
    path:     /affichercour
    defaults: { _controller: BlogBundle:blog:affichercour }
afficherquiz:
    path:     /afficherquiz
    defaults: { _controller: BlogBundle:blog:afficherquiz }
afficherquiz2:
    path:     /afficherquiz2
    defaults: { _controller: BlogBundle:blog:afficherquiz2 }
afficherquiz3:
    path:     /afficherquiz3
    defaults: { _controller: BlogBundle:blog:afficherquiz3 }
scorequiz:
    path:     /scorequiz/{id}
    defaults: { _controller: BlogBundle:blog:scorequiz }
stat:
    path:     /stat
    defaults: { _controller: BlogBundle:backblog:Dashboard }

